Add 2 new IlluminaExperiment types for Illumina sample sheet CSV creation
miso-lims/miso-lims pull request #2533
Opened 2021-06-04 16:27 UTC by peterk87

This PR addresses #2532 adding 2 new IlluminaExperiment types for Application "FASTQ Only" for Assays "Nextera XT" and "TruSeq Nano DNA" for Illumina sample sheet CSV creation.

2021-06-07 14:36 UTC, djcooke requested changes
Change looks good, but please add release notes as described in https://github.com/miso-lims/miso-lims/blob/develop/changes/README.md (add a file to `changes/` that begins with `add_` and contains a brief description of what's being added)

2021-06-07 14:48 UTC, djcooke approved these changes

2021-06-07 14:54 UTC, callunity approved these changes

2021-06-10 14:28 UTC, djcooke commented
Test builds keep failing due to Docker pull limits. It seems the Docker login is not working as expected for docker-maven-plugin. I don't think this change should affect any tests, but I'll keep trying anyway, and will make sure this is merged before the next release

2021-06-10 15:33 UTC, merged